#----------------------------------------------------------------------------------
# clean-build - non-recursive build system based on GNU Make
# Copyright (C) 2015-2017 Michael M. Builov, https://github.com/mbuilov/clean-build
# Licensed under GPL version 2 or any later version, see COPYING
#----------------------------------------------------------------------------------

# note: some project configuration makefile should be already processed before this file,
#  variable TOP must be overridden.
# tip: this file may be built individually via:
# make --eval 'include my_project.mk' -f <this makefile>

include $(dir $(lastword $(MAKEFILE_LIST)))../../stub/defs.mk

# next variables must be defined for this makefile (in project configuration makefile)

# PRODUCT_NAMES_H  - e.g. product_names.h
# VENDOR_NAME      - e.g. Acme Corp
# PRODUCT_NAME     - e.g. Super Product
# VENDOR_COPYRIGHT - e.g. Copyright (C) Acme Corp

# generate product definitions header (e.g. for $(CLEAN_BUILD_DIR)/compilers/msvc/stdres.mk)
GENERATED := $(GEN_DIR)/$(PRODUCT_NAMES_H)
$(call ADD_GENERATED,$(GENERATED))

# <build_num>  - $(firstword $(BUILDNUMBERS))
# <build_date> - $(subst /,-,$(word 2,$(BUILDNUMBERS))) $(word 3,$(BUILDNUMBERS))
define PRODUCT_NAMES_TEMPLATE
#ifndef $(call toupper,$(subst .,_,$(PRODUCT_NAMES_H)))_INCLUDED
#define $(call toupper,$(subst .,_,$(PRODUCT_NAMES_H)))_INCLUDED
#define VENDOR_NAME           "$(VENDOR_NAME)"
#define PRODUCT_NAME          "$(PRODUCT_NAME)"
#define VENDOR_COPYRIGHT      "$(VENDOR_COPYRIGHT)"
#define PRODUCT_VERSION_MAJOR $(call ver_major,$(PRODUCT_VER))
#define PRODUCT_VERSION_MINOR $(call ver_minor,$(PRODUCT_VER))
#define PRODUCT_VERSION_PATCH $(call ver_patch,$(PRODUCT_VER))
#define PRODUCT_OS            "$(OS)"
#define PRODUCT_CPU           "$(CPU)"
#define PRODUCT_KCPU          "$(KCPU)"
#define PRODUCT_TARGET        "$(TARGET)"
#define PRODUCT_BUILD_NUM     <build_num>
#define PRODUCT_BUILD_DATE    "<build_date>"
#endif
endef

# PRODUCT_BUILDNUMBERS - build date, e.g.: 17160 2017/02/16 10:43:09
# note: normally generated by the buildnumber tool based on current date and time
# note: do not inherit PRODUCT_BUILDNUMBERS from the environment here, it may be defined
#  either in command line or taken from the environment in project configuration makefile
PRODUCT_BUILDNUMBERS:=

$(GENERATED): TEMPL := $(PRODUCT_NAMES_TEMPLATE)
$(GENERATED): BUILDNUMBERS := $(PRODUCT_BUILDNUMBERS)
$(GENERATED): $(if $(PRODUCT_BUILDNUMBERS),,| $(call GET_TOOL,buildnumber))
	$(if $(BUILDNUMBERS),,$(eval $@: BUILDNUMBERS := $(shell $(call ospath,$(firstword $|)))))
	$(if $(BUILDNUMBERS),,$(error PRODUCT_BUILDNUMBERS is not defined and failed to get it))
	$(call SUP,GEN,$@)$(call ECHO_TEXT,$(subst <build_date>,$(subst /,-,$(word 2,$(BUILDNUMBERS))) $(word \
  3,$(BUILDNUMBERS)),$(subst <build_num>,$(firstword $(BUILDNUMBERS)),$(TEMPL)))) > $@

$(DEFINE_TARGETS)
