#----------------------------------------------------------------------------------
# clean-build - non-recursive build system based on GNU Make
# Copyright (C) 2015-2017 Michael M. Builov, https://github.com/mbuilov/clean-build
# Licensed under GPL version 2 or any later version, see COPYING
#----------------------------------------------------------------------------------

# normally, some project configuration file should be processed before this file
# tip: this file may be built individually via:
# make --eval 'include my_project.mk' -f <this makefile>

include $(dir $(lastword $(MAKEFILE_LIST)))../../defs.mk

# next variables must be defined for this makefile (for example, in my_project.mk):

# PRODUCT_NAMES_H  - for example, vers.h
# VENDOR_NAME      - for example, Acme Corp
# PRODUCT_NAME     - for example, Super Product
# VENDOR_COPYRIGHT - for example, Copyright (C) Acme Corp

# generate product definitions header
# (this header may be used by $(CLEAN_BUILD_DIR)/WINXX/cres.mk)
GENERATED := $(GEN_DIR)/$(PRODUCT_NAMES_H)
$(call ADD_GENERATED,$(GENERATED))

# <build_num>  - $(firstword $(BUILDNUMBERS))
# <build_date> - $(subst /,-,$(word 2,$(BUILDNUMBERS))) $(word 3,$(BUILDNUMBERS))
define PRODUCT_NAMES_TEMPLATE
#ifndef $(call toupper,$(subst .,_,$(PRODUCT_NAMES_H)))_INCLUDED
#define $(call toupper,$(subst .,_,$(PRODUCT_NAMES_H)))_INCLUDED
#define VENDOR_NAME           "$(VENDOR_NAME)"
#define PRODUCT_NAME          "$(PRODUCT_NAME)"
#define VENDOR_COPYRIGHT      "$(VENDOR_COPYRIGHT)"
#define PRODUCT_VERSION_MAJOR $(call ver_major,$(PRODUCT_VER))
#define PRODUCT_VERSION_MINOR $(call ver_minor,$(PRODUCT_VER))
#define PRODUCT_VERSION_PATCH $(call ver_patch,$(PRODUCT_VER))
#define PRODUCT_OS            "$(OS)"
#define PRODUCT_UCPU          "$(UCPU)"
#define PRODUCT_KCPU          "$(KCPU)"
#define PRODUCT_TARGET        "$(TARGET)"
#define PRODUCT_BUILD_NUM     <build_num>
#define PRODUCT_BUILD_DATE    "<build_date>"
#endif
endef

# PRODUCT_BUILDNUMBERS - normally generated by buildnumber tool based on current date and time,
# may be defined as: 17160 2017/02/16 10:43:09

# note: do not inherit PRODUCT_BUILDNUMBERS from environment,
# to define PRODUCT_BUILDNUMBERS - use command line or project configuration file (via override directive)
PRODUCT_BUILDNUMBERS:=

$(GENERATED): TEMPL := $(PRODUCT_NAMES_TEMPLATE)
$(GENERATED): BUILDNUMBERS := $(PRODUCT_BUILDNUMBERS)
$(GENERATED): $(if $(PRODUCT_BUILDNUMBERS),,| $(call GET_TOOL,buildnumber))
	$(if $(BUILDNUMBERS),,$(eval $@: BUILDNUMBERS := $(shell $(call ospath,$(firstword $|)))))
	$(if $(BUILDNUMBERS),,$(error PRODUCT_BUILDNUMBERS not defined))
	$(call SUP,GEN,$@)$(call ECHO,$(subst <build_date>,$(subst /,-,$(word 2,$(BUILDNUMBERS))) $(word \
  3,$(BUILDNUMBERS)),$(subst <build_num>,$(firstword $(BUILDNUMBERS)),$(TEMPL)))) > $@

$(DEFINE_TARGETS)
