ifneq ($(DLL),)
$(call FORM_TRG,DLL,R): $(call TRG_MAP,DLL)
endif

ifneq ($(DRV),)
DRV_SOURCES := $(call TRG_SRC,DRV)
DRV_TRG := $(call FORM_TRG,DRV)
$(eval $(call ADD_UNIQ_DIR_RULES,$(call FORM_OBJ_DIR,DRV)))
$(eval $(call OBJ_RULES,DRV,CC,$(filter %.c,$(DRV_SOURCES))))
$(eval $(call OBJ_RULES,DRV,ASM,$(filter %.asm,$(DRV_SOURCES))))
$(eval $(call STD_TARGET_VARS,$(DRV_TRG)))
$(eval $(call STD_TARGET_VARS,$(DRV_TRG)))
$(DRV_TRG): SRC        := $(DRV_SOURCES)
$(DRV_TRG): LIB_DIR    := $(LIB_DIR)
$(DRV_TRG): KLIBS      := $(KLIBS)
$(DRV_TRG): INCLUDE    := $(call TRG_INCLUDE,DRV)
$(DRV_TRG): DEFINES    := $(KRNDEFS) $(DEFINES) $(DRV_DEFINES)
$(DRV_TRG): CFLAGS     := $(CFLAGS) $(DRV_CFLAGS)
$(DRV_TRG): ASMFLAGS   := $(ASMFLAGS) $(DRV_ASMFLAGS)
$(DRV_TRG): LDFLAGS    := $(LDFLAGS) $(DRV_LDFLAGS)
DRV_OBJECTS := $(addprefix $(call FORM_OBJ_DIR,DRV)/,$(call OBJS,DRV))
$(DRV_TRG): $(addsuffix $(KLIB_SUFFIX),$(addprefix $(LIB_DIR)/$(KLIB_PREFIX),$(KLIBS))) $(DRV_OBJECTS) | $(BIN_DIR)
	$(call DRV_LD,$@,$(filter %$(OBJ_SUFFIX),$^))
all: $(DRV_TRG)
CLEAN += $(DRV_OBJECTS) $(DRV_TRG)
endif
