#----------------------------------------------------------------------------------
# clean-build - non-recursive build system based on GNU Make
# Copyright (C) 2015-2017 Michael M. Builov, https://github.com/mbuilov/clean-build
# Licensed under GPL version 2 or any later version, see COPYING
#----------------------------------------------------------------------------------

# libtool-archive description file generation

# make name of generated libtool archive
# $1 - name of static version of the library (may be empty if $2 is not empty), e.g. mylib_pie
# $2 - name of dynamic version of the library (may be empty if $1 is not empty), e.g. mylib
# note: there may be multiple variants of static version of the library - position-dependent, PIE, PIC,
#  but only one dynamic (shared) version of the library - position-dependent,
#  make libtool archive name reflect the name of static version, if it exist.
LIBTOOL_ARCHIVE_NAME = lib$(firstword $1 $2).la

# $1 - name of static version of the library (may be empty if $2 is not empty), e.g. mylib_pie
# $2 - name of dynamic version of the library (may be empty if $1 is not empty), e.g. mylib
# $3 - library version (major.minor.patch), e.g. $(MODVER)
# $4 - linker flags
# $5 - dependency libraries, e.g. -ldl
# $6 - weak libraries
# $7 - dlopen name
# $8 - dlpreopen name
# $9 - library installation directory, e.g. $(LIBDIR)/x86_64-linux-gnu
define LIBTOOL_TEXT
# $(LIBTOOL_ARCHIVE_NAME) - a libtool library file
# Generated by clean-build $(CLEAN_BUILD_VERSION) build system
#
# Please DO NOT delete this file!
# It is needed by libtool for linking the library.

# The name that we can dlopen(3).
dlname='$(if $2,lib$2.so$(addprefix .,$(firstword $(subst ., ,$3))))'

# Names of this library.
library_names='$(if $2,$(addprefix lib$2,$(addprefix so.,$3 $(filter-out $3,$(firstword $(subst ., ,$3)))) .so))'

# The name of the static archive.
old_library='$(if $1,lib$1.a)'

# Linker flags that cannot go in dependency_libs.
inherited_linker_flags='$4'

# Libraries that this one depends upon.
dependency_libs='$5'

# Names of additional weak libraries provided by this library
weak_library_names='$6'

# Version information for lib$(firstword $1 $2).
current=$(firstword $(subst ., ,$3) 0)
age=$(firstword $(word 2,$(subst ., ,$3)) 0)
revision=$(firstword $(word 3,$(subst ., ,$3)) 0)

# Is this an already installed library?
installed=yes

# Should we warn about portability when linking against -modules?
shouldnotlink=no

# Files to dlopen/dlpreopen
dlopen='$7'
dlpreopen='$8'

# Directory that this library needs to be installed in:
libdir='$9'
endef

# $1 - name of static version of the library (may be empty if $2 is not empty), e.g. mylib_pie
# $2 - name of dynamic version of the library (may be empty if $1 is not empty), e.g. mylib
# $3 - library version (major.minor.patch), e.g. $(MODVER)
# $4 - linker flags
# $5 - dependency libraries, e.g. -ldl
# $6 - weak libraries
# $7 - dlopen name
# $8 - dlpreopen name
# $9 - library installation directory, e.g. $(LIBDIR)/x86_64-linux-gnu
LIBTOOL_GEN = $(LIBTOOL_TEXT)

$(call SET_GLOBAL,LIBTOOL_ARCHIVE_NAME LIBTOOL_TEXT LIBTOOL_GEN)

## make name of generated .la file
## $1 - static library name (may be empty if $2 is not empty)
## $2 - dynamic library name (may be empty if $1 is not empty)
#GET_LIBTOOL_ARCHIVE_NAME = $(if $1,$(LIB_PREFIX)$1,$(DLL_PREFIX)$2).la
#
## get path to installed .la-file
## $1 - static library name (may be empty if $2 - non-empty)
## $2 - dynamic library name (may be empty if $1 - non-empty)
#INSTALLED_LIBTOOL_ARCHIVE = '$(DESTDIR)$(LIBDIR)/$(GEN_LIBTOOL_ARCHIVE_NAME)'
#
## $1 - all built libraries (result of $(GET_ALL_LIBS))
## $2 - names of built static libraries, may be empty
## $3 - built dynamic library name, may be empty
#INSTALLED_LIBTOOL_ARCHIVES1 = $(foreach r,$1,$(foreach l,$(firstword $(subst ?, ,$r)),$(call \
#  INSTALLED_LIBTOOL_ARCHIVE,$(filter $l,$2),$3)))
#
## get paths to installed .la-files
## $1 - all built libraries (result of $(GET_ALL_LIBS))
## $2 - paths to built static libraries, may be empty
## $3 - path to built dynamic library, may be empty
#INSTALLED_LIBTOOL_ARCHIVES = $(call INSTALLED_LIBTOOL_ARCHIVES1,$1,$(patsubst \
#  $(LIB_PREFIX)%$(LIB_SUFFIX),%,$(notdir $2)),$(patsubst \
#  $(DLL_PREFIX)%$(DLL_SUFFIX),%,$(notdir $3)))
#
## generate contents of .la-file
## $1 - static library name (may be empty if $2 is not empty)
## $2 - dynamic library name (may be empty if $1 is not empty)
#LIBTOOL_ARCHIVE_GENERATOR = $(call LIBTOOL_ARCHIVE_TEMPLATE,$1,$2,$(MODVER))
#
## install .la-file
## $1 - static library name (may be empty if $2 - non-empty)
## $2 - dynamic library name (may be empty if $1 - non-empty)
#INSTALL_LIBTOOL_ARCHIVE = $(call ECHO_INSTALL,$(LIBTOOL_ARCHIVE_GENERATOR),$(INSTALLED_LIBTOOL_ARCHIVE),755)
#
## $1 - all built libraries (result of $(GET_ALL_LIBS))
## $2 - names of built static libraries, may be empty
## $3 - built dynamic library name, may be empty
#INSTALL_LIBTOOL_ARCHIVES1 = $(foreach r,$1,$(foreach l,$(firstword $(subst ?, ,$r)),$(newline)$(call \
#  INSTALL_LIBTOOL_ARCHIVE,$(filter $l,$2),$3)))
#
## install .la-files
## $1 - all built libraries (result of $(GET_ALL_LIBS))
## $2 - paths to built static libraries, may be empty
## $3 - path to built dynamic library, may be empty
#INSTALL_LIBTOOL_ARCHIVES = $(call INSTALL_LIBTOOL_ARCHIVES1,$1,$(patsubst \
#  $(LIB_PREFIX)%$(LIB_SUFFIX),%,$(notdir $2)),$(patsubst \
#  $(DLL_PREFIX)%$(DLL_SUFFIX),%,$(notdir $3)))

#
#
## libcharset.la - a libtool library file
## Generated by ltmain.sh (GNU libtool) 2.2.6
##
## Please DO NOT delete this file!
## It is necessary for linking the library.
#
## The name that we can dlopen(3).
#dlname='../bin/libcharset-1.dll'
#
## Names of this library.
#library_names='libcharset.dll.a'
#
## The name of the static archive.
#old_library='libcharset.a'
#
## Linker flags that can not go in dependency_libs.
#inherited_linker_flags=''
#
## Libraries that this one depends upon.
#dependency_libs=''
#
## Names of additional weak libraries provided by this library
#weak_library_names=''
#
## Version information for libcharset.
#current=1
#age=0
#revision=0
#
## Is this an already installed library?
#installed=yes
#
## Should we warn about portability when linking against -modules?
#shouldnotlink=no
#
## Files to dlopen/dlpreopen
#dlopen=''
#dlpreopen=''
#
## Directory that this library needs to be installed in:
#libdir='/usr/local/lib'
#
